# Generated by Django 4.1.8 on 2023-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="on_free_trail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
