# Generated by Django 4.1.8 on 2023-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_member_user_on_free_trail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="on_free_trail",
            field=models.BooleanField(default=True),
        ),
    ]
