# Generated by Django 4.1.8 on 2023-05-08 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_on_free_trail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="on_free_trail",
            new_name="on_free_trial",
        ),
    ]
